[package]
name = "eueoeo"
version = "0.1.0"
authors = ["perlmint"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
async-trait = "*"
once_cell = "1.7"
serenity = { version = "0.10", default-features = false, features = ["builder", "client", "cache", "gateway", "model", "rustls_backend"] }
tokio = { version = "1.2", features = ["rt-multi-thread", "macros"] }
